### ISSUE TITLE
Migrate from TSLint to Typescript ESLint

### ISSUE THREAD

**Issue by leeren** [google/gts#302]
[TSLint will eventually be deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in favor of [TypeScript ESLint](https://github.com/typescript-eslint/typescript-eslint). It thus makes sense to convert from using `tslint.json` to a customized `.eslintrc.*` file and switch to using `eslint`.

**Comment by vitkarpov** [comment]
@ofrobots makes sense 🤷‍♂️ Would you like a PR for that? I'd do that.

**Comment by ofrobots** [comment]
While it makes sense to switch to `eslint`, but my feeling was that the `eslint+typescript` tooling/ecosystem was not going to be mature enough in time for the `1.0.0` release of `gts` (due out in a couple of weeks).

I think targeting this migration to a `2.0.0` sometime later this year makes more sense?

LMK if my impression is incorrect and if majority of the TypeScript ecosystem has already moved over to using eslint.

**Comment by vitkarpov** [comment]
> TypeScript ecosystem has already moved over to using eslint

I don't think so, Palantir guys have announced it only in February, a couple of months ago. Let's postpone to `2.0.0`, I agree.

**Comment by lindner** [comment]
I've been converting a project that uses gts rules to eslint if anyone wants some inspiration.

https://github.com/PolymerLabs/arcs/blob/master/config/eslintrc.json is the beginning.  Also interested in working with anyone that wants to help push this forward.

**Comment by lindner** [comment]
[also think this issue should get reopened...]

**Comment by david-szabo97** [comment]
Any update on this?

**Comment by JustinBeckwith** [comment]
Nothing yet :)

**Comment by haotangio** [comment]
Hi, do we have any plan to do this yet?

**Comment by JustinBeckwith** [comment]
It's the plan, just haven't had time.  There's a start in #400, but no timeline for it to be done yet.

**Comment by StephenHaney** [comment]
Just chipping in some perspective: we're considering moving back to TSLint until the typescript-eslint repo matures.

Since migrating to ESLint, we've had A LOT of problems with really bad performance and poor TypeScript support with the vscode-eslint extension; it often crashes, gives odd errors, or hangs at 99% CPU (although this appears to be recently remedied).

Since moving to ESLint for TS, we're spending way too much time talking about debugging our linter.

I'm not saying don't do it – there are lots of talented people working hard on typescript-eslint, so I have no doubt it will soon become the clear choice. But I'm not sure the VSCode extension support is there yet, and make sure to test it well and weigh the trade-offs of leaving a more mature setup.

**Comment by catgirlsec** [comment]
What changes are still needed to make this happen?

**Comment by JustinBeckwith** [comment]
Mostly need to discuss the changes in #400, and add a lot of tests.

**Comment by JustinBeckwith** [comment]
This is complete, and will be in the 2.x release :)
